# Generated by Django 4.2.5 on 2023-09-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(default='Staff', max_length=100),
        ),
    ]
