# Generated by Django 4.2.5 on 2023-09-15 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
